import{useEffect,useState}from'react';
import{ArrowUpRight,Check,ChevronRight,CircleDot,Database,ExternalLink,FileSearch2,Orbit,RefreshCw,ShieldCheck,Wallet,X}from'lucide-react';
import type{CalldataEncodable}from'genlayer-js/types';
import{CONTRACT,configured,connect,explorer,read,short,txUrl,write}from'./genlayer';
import{latestCaseEpochId}from'./caseEpoch';
type Item={id:number;brand:string;upc:string;lot_code:string;best_by:string;state_code:string;status:string;reason:string};type Log={label:string;hash:string};
const stages=['COLLECT','LOCK','RESOLVE','ARCHIVE'];
export default function App(){const[account,setAccount]=useState('');const[busy,setBusy]=useState('');const[error,setError]=useState('');const[counts,setCounts]=useState<any>(null);const[caseId,setCaseId]=useState('1');const[dossier,setDossier]=useState<any>(null);const[items,setItems]=useState<Item[]>([]);const[epoch,setEpoch]=useState<any>(null);const[logs,setLogs]=useState<Log[]>([]);const cid=Number(caseId)||0;
 const[view,setView]=useState<'console'|'submit'>('console');
 const sync=async()=>{if(!configured)return;setError('');try{const[c,d]=await Promise.all([read<any>('get_counts'),cid?read<any>('get_case',[cid]):null]);const latestEpochId=latestCaseEpochId(d);setCounts(c);setDossier(d);setItems(await Promise.all((d?.item_ids||[]).map((id:number)=>read<Item>('get_item',[id]))));setEpoch(latestEpochId?await read('get_epoch',[latestEpochId]):null)}catch(e){setError(msg(e))}};useEffect(()=>{void sync()},[cid]);
 const send=async(label:string,fn:string,args:CalldataEncodable[])=>{setBusy(label);setError('');try{if(!account)throw Error('Connect a wallet before signing.');const hash=await write(account,fn,args);setLogs(v=>[{label,hash},...v]);await sync()}catch(e){setError(msg(e))}finally{setBusy('')}};
 const make=async()=>{await send('Create case','create_case',['Frozen berry recall scope audit']);const c=await read<any>('get_counts');setCaseId(String(c.cases))};const active=dossier?.status==='SEALED'?(epoch?.id?3:2):items.length?1:0;
 return <div className="shell"><aside className="rail"><button className="mark" onClick={()=>setView('console')}><img src="/recallradius-logo.png"/></button><nav><button aria-label="Operations console" className={view==='console'?'active':''} onClick={()=>setView('console')}><Orbit/></button><button aria-label="Submission desk" className={view==='submit'?'active':''} onClick={()=>setView('submit')}><FileSearch2/></button><a aria-label="Public ledger" href="#ledger" onClick={()=>setView('console')}><Database/></a></nav><div className="railFoot"><i/>STUDIO<br/>61997</div></aside><div className="surface" id="top">
 <header><div><p>RECALL OPERATIONS / FDA_BLUEBERRY_2026</p><h1>RecallRadius</h1></div><div className="headActions"><button className="sync" onClick={sync}><RefreshCw/>Sync finalized</button><button className="wallet" onClick={async()=>{try{setAccount(await connect())}catch(e){setError(msg(e))}}}><Wallet/>{account?short(account):'Connect wallet'}</button></div></header>{error&&<div className="error"><X/>{error}</div>}
 {view==='submit'?<SubmissionDesk account={account} busy={busy} caseId={caseId} setCaseId={setCaseId} send={send} make={make}/>:<main id="workspace"><section className="ticker"><div><small>CASES</small><b>{counts?.cases??'—'}</b></div><div><small>REGISTERED ITEMS</small><b>{counts?.items??'—'}</b></div><div className="network"><CircleDot/><span>FINALIZED STATE</span><strong>{configured?'ONLINE':'UNCONFIGURED'}</strong></div></section>
 <section className="mission"><div className="missionCopy"><span className="index">01 / SCOPE MISSION</span><h2>Trace the boundary.<br/><em>Not the headline.</em></h2><p>Validators normalize one fixed FDA notice. Deterministic code intersects UPC, lot, date and distribution—then preserves every scope epoch.</p><a href="https://www.fda.gov/food/outbreaks-foodborne-illness/outbreak-investigation-e-coli-o145h28-frozen-blueberries-july-2026" target="_blank">Open fixed FDA source <ArrowUpRight/></a></div><div className="radar"><div className="ring r1"/><div className="ring r2"/><div className="ring r3"/><div className="sweep"/><img src="/recallradius-logo.png"/><span className="ping p1"/><span className="ping p2"/><div className="radarLabel">BOUNDED<br/>SOURCE</div></div></section>
 <section className="workflow"><div className="sectionHead"><div><span className="index">02 / CASE WORKBENCH</span><h2>One batch. Independent wallets.</h2></div><label className="caseSwitch"><span>CASE SELECTOR</span><b>#</b><input aria-label="Case ID" value={caseId} onChange={e=>setCaseId(e.target.value)}/></label></div>
 <div className="stageLine">{stages.map((s,i)=><div className={i<=active?'done':''} key={s}><span>{i<active?<Check/>:i+1}</span><b>{s}</b><small>{['wallet submissions','creator seal','validator epoch','immutable readback'][i]}</small></div>)}</div>
 <div className="composer"><div className="caseMeta"><small>ACTIVE DOSSIER</small><h3>{dossier?.title||'No case loaded'}</h3><div><span className={`status ${dossier?.status||''}`}>{dossier?.status||'WAITING'}</span><code>REV {dossier?.revision??'—'}</code></div></div><div className="commands"><button disabled={!!busy||!configured} onClick={make}><span>01</span><b>Open a fresh batch</b><small>Any connected wallet</small><ChevronRight/></button><button disabled={!dossier||dossier?.status==='SEALED'} onClick={()=>send('Register affected item','register_item',[cid,'GreenWise','41415-06453','ANYLOT','2028-02-09','FL'])}><span>02A</span><b>Add affected fixture</b><small>GreenWise · Florida</small><ChevronRight/></button><button disabled={!dossier||dossier?.status==='SEALED'} onClick={()=>send('Register control item','register_item',[cid,'Other Brand','999999999999','SAFE77','2028-02-09','FL'])}><span>02B</span><b>Add negative control</b><small>Independent wallet</small><ChevronRight/></button><button disabled={!dossier||dossier?.status==='SEALED'} onClick={()=>send('Seal batch','seal_case',[cid])}><span>03</span><b>Seal registered scope</b><small>Case creator only</small><ChevronRight/></button><button className="resolve" disabled={dossier?.status!=='SEALED'} onClick={()=>send('Assess FDA epoch','assess_epoch',[cid,Number(dossier?.revision||0)])}><span>04</span><b>{busy==='Assess FDA epoch'?'Validators reading…':'Resolve next epoch'}</b><small>Permissionless trigger</small><ChevronRight/></button></div></div>
 <div className="manifest"><div className="manifestHead"><span>ITEM MANIFEST</span><span>FIELD INTERSECTION</span><span>FINAL VERDICT</span></div>{items.map(i=><article key={i.id}><div className="itemId">{String(i.id).padStart(2,'0')}</div><div><b>{i.brand}</b><small>UPC {i.upc}</small></div><div className="fields"><code>LOT/{i.lot_code}</code><code>DATE/{i.best_by}</code><code>GEO/{i.state_code}</code></div><div className={`verdict ${i.status}`}><i/><b>{i.status}</b><small>{i.reason}</small></div></article>)}{!items.length&&<div className="manifestEmpty">No products registered in this dossier.</div>}</div></section>
 <section className="sourceGrid" id="source"><div className="epochPanel"><span className="index">03 / SOURCE EPOCH</span><div className="epochNum">{epoch?.id?String(epoch.id).padStart(2,'0'):'—'}</div><h2>{epoch?.status||'AWAITING ASSESSMENT'}</h2><p>{epoch?.scope_transition||'No scope transition recorded'}</p><code>{epoch?.source_digest||'Source digest will appear after validator consensus.'}</code></div><div className="rules"><div><b>AI boundary</b><p>Normalize a closed fact tuple only.</p></div><div><b>Contract boundary</b><p>Derive every product verdict deterministically.</p></div><div><b>Failure posture</b><p>Malformed evidence resolves to SOURCE_UNAVAILABLE.</p></div><div><ShieldCheck/><b>No custody<br/>No deployer privilege</b></div></div></section>
 <section className="ledger" id="ledger"><div className="sectionHead"><div><span className="index">04 / PUBLIC LEDGER</span><h2>Reviewer readback</h2></div>{explorer&&<a href={explorer} target="_blank">Contract explorer <ExternalLink/></a>}</div><div className="ledgerRows"><div><span>CONTRACT</span><code>{CONTRACT}</code></div><div><span>ARCHITECTURE</span><code>append-only-scope-epochs-deterministic-intersection</code></div><div><span>SOURCE</span><code>FDA_BLUEBERRY_2026</code></div>{logs.map(l=><a href={txUrl(l.hash)} target="_blank" key={l.hash}><span>{l.label.toUpperCase()}</span><code>{l.hash}</code><ExternalLink/></a>)}</div></section></main>}<footer><span>RecallRadius / public-source recall scope</span><span>Classification aid—not medical advice.</span></footer></div></div>}

function SubmissionDesk({account,busy,caseId,setCaseId,send,make}:any){const[title,setTitle]=useState('My recall scope review');const[form,setForm]=useState({brand:'',upc:'',lot:'',bestBy:'2028-02-09',state:'FL'});const field=(key:string)=>(e:any)=>setForm(v=>({...v,[key]:e.target.value}));return <main className="submission"><div className="submitIntro"><span className="index">NEW / SUBMISSION DESK</span><h2>Bring your own<br/>product record.</h2><p>This is the transaction workspace. A reviewer can connect any Studio Next wallet, create a dossier, and register a real product record without using pre-filled fixtures.</p><div className="identity"><span>ACTIVE SIGNER</span><code>{account||'WALLET NOT CONNECTED'}</code></div></div><div className="forms"><section><div className="formHead"><span>01</span><div><b>Open a dossier</b><small>Creates a new case owned by the connected wallet.</small></div></div><label>CASE TITLE<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Store inventory review"/></label><button disabled={!account||!!busy||title.trim().length<5} onClick={()=>send('Create custom case','create_case',[title.trim()])}>Create dossier <ChevronRight/></button></section><section><div className="formHead"><span>02</span><div><b>Register a product</b><small>The connected wallet becomes this item's registrant.</small></div></div><div className="formGrid"><label>CASE ID<input value={caseId} onChange={e=>setCaseId(e.target.value)}/></label><label>BRAND<input value={form.brand} onChange={field('brand')} placeholder="GreenWise"/></label><label>UPC<input value={form.upc} onChange={field('upc')} placeholder="41415-06453"/></label><label>LOT CODE<input value={form.lot} onChange={field('lot')} placeholder="6040 01-6"/></label><label>BEST-BY DATE<input type="date" value={form.bestBy} onChange={field('bestBy')}/></label><label>STATE / TERRITORY<input maxLength={2} value={form.state} onChange={field('state')} placeholder="FL"/></label></div><button disabled={!account||!!busy||!form.brand||!form.upc||!form.lot} onClick={()=>send('Register custom product','register_item',[Number(caseId),form.brand,form.upc,form.lot,form.bestBy,form.state.toUpperCase()])}>Register product <ChevronRight/></button></section><div className="submitNote"><ShieldCheck/><p><b>Reviewer-safe by design.</b><br/>No allowlist or deployer permission is required. Only the registrant may edit its product before the case creator seals the batch.</p></div></div></main>}
function msg(e:unknown){return e instanceof Error?e.message:String(e)}
