import{useEffect,useState}from'react';import{AlertTriangle,ArrowRight,ExternalLink,FileCheck2,LocateFixed,RefreshCw,ScanLine,ShieldCheck,Wallet}from'lucide-react';import type{CalldataEncodable}from'genlayer-js/types';import{CONTRACT,configured,connect,explorer,read,short,txUrl,write}from'./genlayer';
type Item={id:number;brand:string;upc:string;lot_code:string;best_by:string;state_code:string;status:string;reason:string;revision:number};type Log={label:string;hash:string};
export default function App(){const[account,setAccount]=useState('');const[busy,setBusy]=useState('');const[error,setError]=useState('');const[counts,setCounts]=useState<any>(null);const[caseId,setCaseId]=useState('1');const[itemId,setItemId]=useState('1');const[dossier,setDossier]=useState<any>(null);const[items,setItems]=useState<Item[]>([]);const[epoch,setEpoch]=useState<any>(null);const[logs,setLogs]=useState<Log[]>([]);const cid=Number(caseId)||0;
 const sync=async()=>{if(!configured)return;setError('');try{const[c,d]=await Promise.all([read<any>('get_counts'),cid?read<any>('get_case',[cid]):null]);setCounts(c);setDossier(d);setItems(await Promise.all((d?.item_ids||[]).map((id:number)=>read<Item>('get_item',[id]))));setEpoch(c?.epochs?await read('get_epoch',[Number(c.epochs)]):null)}catch(e){setError(msg(e))}};useEffect(()=>{void sync()},[]);
 const send=async(label:string,fn:string,args:CalldataEncodable[])=>{setBusy(label);setError('');try{if(!account)throw Error('Connect a wallet before signing.');const hash=await write(account,fn,args);setLogs(v=>[{label,hash},...v]);await sync()}catch(e){setError(msg(e))}finally{setBusy('')}};
 const make=async()=>{await send('Create case','create_case',['Frozen berry recall scope audit']);const c=await read<any>('get_counts');setCaseId(String(c.cases));};
 const affected=()=>send('Register affected item','register_item',[cid,'GreenWise','41415-06453','ANYLOT','2028-02-09','FL']);const control=()=>send('Register control item','register_item',[cid,'Other Brand','999999999999','SAFE77','2028-02-09','FL']);const seal=()=>send('Seal batch','seal_case',[cid]);const assess=()=>send('Assess FDA epoch','assess_epoch',[cid,Number(dossier?.revision||0)]);
 return <><header><a className="brand" href="#top"><img src="/recallradius-logo.png"/><span>RecallRadius<small>FDA Scope Resolver</small></span></a><nav><a href="#batch">Batch</a><a href="#scope">Scope engine</a><a href="#audit">Audit</a></nav><b className="net">Studio Next · 61997</b><button onClick={async()=>{try{setAccount(await connect())}catch(e){setError(msg(e))}}}><Wallet size={16}/>{account?short(account):'Connect wallet'}</button></header>{error&&<div className="error">{error}</div>}<main id="top">
 <section className="hero"><div><p className="eyebrow">OFFICIAL SOURCE · DETERMINISTIC MATCHING</p><h1>Find the exact edge<br/>of a food recall.</h1><p>RecallRadius turns a changing FDA advisory into append-only scope epochs, then deterministically intersects each registered product with the normalized UPC, lot, date and distribution fields.</p><div className="actions"><a className="primary" href="#batch">Open scope console <ArrowRight/></a><a href="https://www.fda.gov/food/outbreaks-foodborne-illness/outbreak-investigation-e-coli-o145h28-frozen-blueberries-july-2026" target="_blank">FDA advisory <ExternalLink/></a></div></div><div className="heroArt"><img src="/recallradius-logo.png"/><span><ShieldCheck/> No custody. No deployer privilege.</span></div></section>
 <section className="stats"><div><b>{counts?.cases||0}</b><span>Cases</span></div><div><b>{counts?.items||0}</b><span>Items</span></div><div><b>{counts?.epochs||0}</b><span>Scope epochs</span></div><div><b>FDA</b><span>Fixed authority</span></div></section>
 <section id="batch"><div className="sectionTitle"><div><p className="eyebrow">MULTI-WALLET BATCH</p><h2>Register first. Resolve together.</h2></div><button className="ghost" onClick={sync}><RefreshCw/>Read finalized state</button></div>{!configured&&<div className="warning">Contract address has not been configured.</div>}<div className="workspace"><aside><h3>Case controls</h3><button className="primary" disabled={!!busy||!configured} onClick={make}>Create open case</button><label>Case ID<input value={caseId} onChange={e=>setCaseId(e.target.value)}/></label><button onClick={affected}>Register affected fixture</button><button onClick={control}>Register negative control</button><button className="seal" onClick={seal}>Seal two-wallet batch</button><button className="danger" onClick={assess}>{busy==='Assess FDA epoch'?'Validators reading FDA…':'Assess new FDA epoch'}</button></aside><article><div className="caseHead"><div><small>CASE #{cid}</small><h3>{dossier?.title||'No case loaded'}</h3></div><b className={dossier?.status||''}>{dossier?.status||'—'}</b></div><div className="items">{items.map(i=><button key={i.id} onClick={()=>setItemId(String(i.id))} className={Number(itemId)===i.id?'active':''}><span>#{i.id}</span><div><b>{i.brand}</b><small>UPC {i.upc} · lot {i.lot_code}<br/>{i.best_by} · {i.state_code}</small></div><em className={i.status}>{i.status}<small>{i.reason}</small></em></button>)}{!items.length&&<p className="empty">Create a case, then let two independent wallets register products.</p>}</div></article></div></section>
 <section id="scope" className="scope"><p className="eyebrow">APPEND-ONLY SCOPE ENGINE</p><h2>AI extracts facts. Contract decides matches.</h2><div className="flow"><article><ScanLine/><b>1 · Normalize</b><p>Validators read one fixed FDA advisory and agree on a closed scope tuple.</p></article><article><LocateFixed/><b>2 · Intersect</b><p>Contract code matches UPC, lot, best-by and state—never an AI payout or free-form verdict.</p></article><article><FileCheck2/><b>3 · Preserve delta</b><p>Every epoch retains its source digest, scope digest, field diagnostics and status transition.</p></article></div><div className="epoch"><span>Latest epoch</span><b>{epoch?.id?`#${epoch.id} · ${epoch.status}`:'Not assessed'}</b><code>{epoch?.scope_transition||'—'}</code><code>{epoch?.source_digest||'Digest appears after assessment'}</code></div></section>
 <section id="audit"><p className="eyebrow">REVIEWER AUDIT</p><h2>Nothing important is hidden in the UI.</h2><div className="audit"><div><span>Contract</span><code>{configured?CONTRACT:'Not deployed'}</code>{explorer&&<a href={explorer} target="_blank">Explorer <ExternalLink/></a>}</div><div><span>Source</span><a href="https://www.fda.gov/food/outbreaks-foodborne-illness/outbreak-investigation-e-coli-o145h28-frozen-blueberries-july-2026" target="_blank">FDA blueberry advisory <ExternalLink/></a></div><div><span>Architecture</span><code>append-only scope epochs</code></div></div><div className="logs">{logs.map(l=><a href={txUrl(l.hash)} target="_blank" key={l.hash}><b>{l.label}</b><code>{short(l.hash)}</code><ExternalLink/></a>)}</div><p className="note"><AlertTriangle/> Scope classification helps identify products for review. Follow the current FDA advisory and public-health guidance; this application is not medical advice.</p></section></main><footer>RecallRadius · public-source recall scope on GenLayer</footer></>}
function msg(e:unknown){return e instanceof Error?e.message:String(e)}
